#!/bin/bash
set -e

# Docker entrypoint script for runtime environment variable injection
# This script generates /usr/share/nginx/html/env.js with environment variables
# that can be accessed in the React application via window.env

echo "🔧 Generating runtime environment configuration..."

# Default values for local development
BACKEND_URL="${BACKEND_URL:-http://localhost:7008}"
ENV="${ENV:-development}"

# Generate env.js file
cat > /usr/share/nginx/html/env.js << EOF
// Runtime environment variables
// Generated by docker-entrypoint.sh at container startup
// DO NOT EDIT - This file is auto-generated

window.env = {
  BACKEND_URL: "${BACKEND_URL}",
  ENV: "${ENV}"
};

console.log('✅ Runtime environment loaded:', window.env);
EOF

echo "✅ Environment configuration generated successfully"
echo "   BACKEND_URL: ${BACKEND_URL}"
echo "   ENV: ${ENV}"
echo ""
echo "🚀 Starting Nginx..."

# Execute the CMD (start nginx)
exec "$@"

